### ISSUE TITLE
(QUESTION) How to specify a custom SMTP service?, instead of a 'well-known service'

### ISSUE THREAD

**Issue by luisincrespo** [balderdashy/sails-hook-email#11]
Hi.

In the configs you have a service attribute to specify a 'well known service', what if I want to specify a custom SMTP service?.

**Comment by jetsonjohn** [comment]
+1 
I have to do the same.

**Comment by Maxtermax** [comment]
+1 
 same question

**Comment by tinkusam** [comment]
Use the 'transporter' option under sails.config.email which will override 'service' and 'auth' options.

``` javascript
....
transporter: {
  host: 'smtpout.secureserver.net', // Godaddy SMTP server
  port: 465,
  secure: true,
  auth: {
    user: "<mail account username>",
    pass: "<mail account password>"
  }
},
...
```

**Comment by sgress454** [comment]
Thanks @tinkusam.  If someone wants to put in a PR to add that to the docs, they are welcome!
