### ISSUE TITLE
Can not define a custom template

### ISSUE THREAD

**Issue by leosuncin** [balderdashy/sails-hook-email#16]
When I use a custom template name on email hook, as you see next

```
sails.hooks.email.send('welcome',templateData, mailOptions, cb);
```

Throws this error `error: Error: ENOENT, open 'views/emailTemplates/welcome/html.ejs'`, I would expect 'views/emailTemplates/welcome.ejs'

Post data: can you add compatibility to use promise? as:

```
sails.hooks.email.send(template, data, options).then(function(result) {
// Some code here
}).catch(function(err) {
// Error handling here
})
```

**Comment by sgress454** [comment]
> I would expect 'views/emailTemplates/welcome.ejs'

Please see the [documentation on templates](https://github.com/balderdashy/sails-hook-email#templates).

> Post data: can you add compatibility to use promise?

Sounds like a good PR for somebody... :)

**Comment by leosuncin** [comment]
Is there a way to use a different template of by default? for some case use welcome.ejs instead of html.ejs
