### ISSUE TITLE
How to use this with 0.10.5?

### ISSUE THREAD

**Issue by cwoloszynski** [balderdashy/sails-hook-email#4]
I am uncomfortable switching from sails 0.10.5 to 0.10.6 (I am a newbie to Sails and want to stay in the mainstream AMAP) but I need a mail solution for my sails app.    

Are there any plans for instructions on how to use this under 0.10.5 or do I need to wait for 0.10.6 to become mainstream?

**Comment by sgress454** [comment]
This is really intended for the next version of Sails, to show how installable hooks work, but you can [follow this](https://github.com/balderdashy/sails-hook-email/pull/2/files) from @chalettu to try in v0.10.5.  You'll also have to `npm install nodemailer@0.7.1`.
