### ISSUE TITLE
Getting warning on lift

### ISSUE THREAD

**Issue by adavia** [balderdashy/sails-hook-email#6]
Any idea why after installing this hook i get warn: [Function] when i lift my app?

**Comment by sgress454** [comment]
Kinda hard to say without any more details.  Is it on a new app?  Did you set any configuration in the hook?

**Comment by adavia** [comment]
No config in the hook.
It works fine actually. Im just getting this warning only which is kinda annoying.

**Comment by sgress454** [comment]
I don't see anyplace in the hook or in nodemailer that does a `console.warn`, and I can't reproduce this.  So I'm guessing that either you already had a different version of nodemailer installed, or there's something else going on with your particular app.  Try `npm uninstall sails-hook-email`, `npm cache clean` and `npm install sails-hook-email` again.  Closing this as it doesn't appear to be an issue with the hook itself, but post back if you figure anything out!
